spring.application.name=Newsletter_And_Email_Manager_Campain
server.port=8088

# This forces the connection to 'NewsletterDB'
spring.data.mongodb.uri=mongodb://localhost:27017/NewsletterDB
spring.data.mongodb.auto-index-creation=true
